name: Lint CSS
on: 
    push:
        branches:
            - develop
    pull_request:
        branches:
            - master

jobs:
  linters:
    name: stylelint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/stylelint@master